### ISSUE TITLE
The docker image has been removed from the GCR registry

### ISSUE THREAD

**Issue by wilmardo** [bitnami-labs/charts-syncer#187]
As the title states, since the last 24h or so the images has been removed from GCR

```console
# docker pull gcr.io/bitnami-labs/charts-syncer:v0.20.1
Error response from daemon: Head "https://gcr.io/v2/bitnami-labs/charts-syncer/manifests/v0.20.1": denied: Project bitnami-labs has been deleted.
```

Was this intentional?

**Comment by jotadrilo** [comment]
Hello!

I am sorry for the inconvenience! The team is checking it and I will come back to you as soon as we can.

**Comment by beltran-rubo** [comment]
We apologize for the inconvenience, this was an infrastructure change that affected the registry. It as been recovered and it is fully working now. Thanks for reporting it. We are working on adding the mechanisms that would not happen again in future releases of the container image.

**Comment by fplantinga-guida** [comment]
This was working again, but since the 4th of november, we are having issue again. 

λ ~/ docker pull gcr.io/bitnami-labs/charts-syncer:v0.20.1                                                                                                                                
Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication

**Comment by AstritCepele** [comment]
@beltran-rubo  This issue is still present and must opened.

**Comment by beltran-rubo** [comment]
There was in infrastructure issue on Nov the 4th-5th, it is working since Nov the 6th.

**Comment by fplantinga-guida** [comment]
I can confirm it is working again.
